### ISSUE TITLE
Add User Management to Light Install

### ISSUE THREAD

**Issue by narbit** [brunohbrito/JPProject.IdentityServer4.AdminUI#246]
Question that is exactly opposite to #110 :) Currently Light Install only allows to manage resources (clients, grants, etc.) for the existing IdP. As such UI links for user management are broken in the admin panel. 

If I wanted to include user management functionality, would it be as simple as copying UserControler and UserManagementController from JPProject.IdentityServer4.SSO/src/Backend/Jp.Api.Management/Controllers into JPProject.IdentityServer4.AdminUI/src/Backend/JPProject.Admin.Api/Controllers? I have an existing IdP that uses ASP.NET Core Identity. 

Thank you!

**Comment by brunohbrito** [comment]
Hi Natalya @narbit,

Yes, it's possible... but (there is always a "but") will be simple only if you have a default ASP.NET Identity config. What it means?

Your UserId is string without custom properties. Them the actual implementation will force you to use the class `UserIdentity` as your User object.

Why not simpler? The biggest problem is that ASP.NET Core Identity is really flexible with a lot of possibilities. So instead keep project full compatible with Identity (I tried and still have no clue how to accomplish it) I've decided to provide this light version. The full version is a pre configured asp identity.

If you wanna go ahead, you need to fork https://github.com/brunohbrito/JPProject.Core and change `SSOBootstrapper.cs` to match your Identity settings.

**Comment by brunohbrito** [comment]
Hi @narbit 

One item of the new version in my roadmap was a try to decouple ASP.NET Identity. I've accelerated the development because some requests like yours.

The PR https://github.com/brunohbrito/JPProject.IdentityServer4.SSO/pull/28 introduce the configuration of ASP.NET Identity within SSO project and you have almos total control over ASP.NET Identity.

Maybe the boring part is that you need to implement `IDomainUser`, because it Add some fields to your IdentityUser implementation.

In next release all these fields will be Claims, instead database fields, giving you total control over ASP.NET Identity.

**Comment by narbit** [comment]
@brunohbrito , this is nice, thank you!

Since I am using Light Install, I've added UserController to API-Light project with all the expected user management end-points. I referred to SSO and Core projects to figure out the plumbing for all the service calls. Then just coded them myself. It was not too much work in the end :)
