### ISSUE TITLE
Add Blazor UI

### ISSUE THREAD

**Issue by yehia2amer** [brunohbrito/JPProject.IdentityServer4.AdminUI#294]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
First of all thanks a lot for this awesome project. I Really like the Architecture.

My Question is: Since there is responsibility separation concerns, SOLID, DDD, CQRS, etc.
It should be easier to Add Blazor, so that the user can choose between Angular or Blazor for the UI !

Any Plans to do so, or anyone even exited about this idea ? I Really feel that this project could be a Great starting point to do so !

**Comment by brunohbrito** [comment]
Hi @yehia2amer ,

Its a great idea, but in a way I've to choose: New Features or New UI. I don't have enough time for both.

You are right to say that it'll be easy to build another UI, since the solution was built in Hexagonal Architecture. But Blazor UI isn't in my roadmap since it will be just an alternative for a Angular 8. My focus right now is to add new Features to [SSO](https://github.com/brunohbrito/JPProject.IdentityServer4.SSO) and provide Device flow for Admin UI.

So feel free to clone / fork project and build a new UI in Blazor. I'm sure that will be a great study case for Blazor!

**Comment by yehia2amer** [comment]
I completely understand your point.
Since you mentioned SSO, There is almost no JS there, so it should be the most logical step to start with it. I am not sure I do have time too, but if I do, I will start with SSO !

**Comment by yehia2amer** [comment]
Related to this issue, I think it would be useful for anyone thinking of doing the same:

https://github.com/dotnet/aspnetcore/issues/21199
