### ISSUE TITLE
Extending user entity

### ISSUE THREAD

**Issue by ekjuanrejon** [brunohbrito/JPProject.IdentityServer4.AdminUI#30]
What is the easiest way of extending the user entity to add more columns. 

If you take a look skoruba admin for entity Framework it generates nuget packages and then anyone can extend the user entity

https://github.com/skoruba/IdentityServer4.Admin

**Comment by brunohbrito** [comment]
Quickly answer your question:
The Identity Framework was isolated at `Jp.Infra.CrossCutting.Identity`. So if you wanna new properties for users, even changing the Id to int, you've to change Entities files there.

For Users, the file is `Jp.Infra.CrossCutting.Identity.Entities.Identity.UserIdentity.cs`

If you add new data or change the actual, then you have to track Profile models at 
* `Jp.Application.Services.UserAppService` 
  * `UserViewModel`
* `Jp.Application.Services.UserManagerAppService`
  * UpdateProfile(UserViewModel model)

If you pretend to use **User Management UI**, then you have to change Profile component:
* JP-Project\src\Frontend\Jp.UserManagement\src\app\management\user\profile

---------------------------------------------------------------

Forgive my ignorance, but I can't see benefits by generating my own packages and providing for developers the ability to extend User Identity, because Identity itself have done that. 

I'll appreciate if you can give me an explanation! And I'll check how Skoruba have done that.

What I've thought is to deliver an easy way to change Identity config by isolating it.

**Comment by ekjuanrejon** [comment]
Thanks for the explanation. I suppose I want to add couple more fields to the user entity for a multi tenant application

**Comment by ekjuanrejon** [comment]
But I guess I can fork the repo and the fields and build the new docker image
